name: CI
on:
  push:
    branches: [beta, main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    name: Build, lint, and test on Node 16.x
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test --ci --coverage --maxWorkers=2

      - name: Build
        run: npm run build

      - name: Run semantic-release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          branches: |
            [
              'main', 
              {
                name: 'beta', 
                prerelease: true
              }
            ]
